# Generated by Django 5.2.4 on 2025-07-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0004_singer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='image',
        ),
        migrations.CreateModel(
            name='SingerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='singer_images/')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='singer.singer')),
            ],
        ),
    ]
