# Generated by Django 5.2.4 on 2025-07-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0005_remove_singer_image_singerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='genre',
            field=models.CharField(default='기타', max_length=50),
        ),
        migrations.AddField(
            model_name='singer',
            name='member_count',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='singer',
            name='name',
            field=models.CharField(default='임시이름', max_length=100),
        ),
    ]
