# Generated by Django 5.2.4 on 2025-07-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0006_singer_genre_singer_member_count_singer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='임시제목', max_length=100),
        ),
    ]
